# Generated by Django 6.1.1 on 2026-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_estreno', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
